
name: CI/CD Laravel
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: itokaken_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      # PHP setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.2
          extensions: mbstring, bcmath
      - name: copy .env
        run: cp .env.ci .env  
      - name: composer install
        run: composer install

      # PHPCS - PHPMD check
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: PHP conventions check
        run:  |
            for changed_file in ${{ steps.files.outputs.added_modified }}; do
              ./vendor/bin/phpcs ${changed_file}
            done
      - name: PHP mess detector
        run:  |
            for changed_file in ${{ steps.files.outputs.added_modified }}; do
              ./vendor/bin/phpmd ${changed_file} text phpmd.xml
            done
      
      # Unit test
      - name: generate key
        run: php artisan key:generate
      - name: Run unit tests
        # Run unit test below ex. ./vendor/bin/phpunit
        run: |
          php artisan migrate --env=ci
